### ISSUE TITLE
Adding Value to Promo Codes 

### ISSUE THREAD

**Issue by Temian1** [zgabievi/Promocodes#96]
is there a way to for each promocodes to have a value
1 promo code has 50 value

**Comment by zgabievi** [comment]
Promocodes do have value. Can you explain better, what you need to achieve?

**Comment by Allgoodnamesargone** [comment]
> Promocodes do have value. Can you explain better, what you need to achieve?

He most probably looking for something like #92
Guess he wants to set for example $50 for the Promocode and whoever that apply the promocode get $50 added to his balance.
However, by looking at `->details([ 'discount' => 50 ])` it seems that it's already possible, the better version would be #92 

-----
not related to this issue, but i just found a minor typo in readme. `fill free to open issue`

Thanks for the package, i have to use it in the near future.
